name: my_yaru_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.3"

dependencies:
  flutter:
    sdk: flutter
  handy_window: ^0.4.0
  yaru:
    git:
      url: https://github.com/ubuntu/yaru.dart
      ref: 48d0c6790da12a53c3f151936fe5e1573f7ea389


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
